services:
  - type: web
    name: docusign-iam-demo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DOCUSIGN_INTEGRATION_KEY
        sync: false
      - key: DOCUSIGN_CLIENT_SECRET
        sync: false
      - key: DOCUSIGN_ACCOUNT_ID
        sync: false
      - key: DOCUSIGN_BASE_URI
        value: https://demo.docusign.net
      - key: DOCUSIGN_REDIRECT_URI
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
